### ISSUE TITLE
N18 - Avoid using `transfer()` to transfer ETH

### ISSUE THREAD

**Issue by PhABC** [arcadeum/erc20-meta-wrapper#9]
![image](https://user-images.githubusercontent.com/9306422/71834899-50554700-307e-11ea-9cfc-8ac0c520b096.png)

By @Agusx1211

**Comment by PhABC** [comment]
What would be the purpose of the reentrancy check? It looks like re-entrancy is not problematic in this case.

**Comment by Agusx1211** [comment]
It should pose an issue, in that case, the reentrancy lock shouldn’t be needed.

That being said, replacing `transfer()` with `call.vale()` should be enough to fix the issue.
